"""proximity col name update

Revision ID: 543375f6316e
Revises: f5be92522762
Create Date: 2025-02-05 11:40:32.756985

"""
from typing import Sequence, Union
from geoalchemy2 import Geometry
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543375f6316e'
down_revision: Union[str, None] = 'f5be92522762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    # Rename the column from 'traffic_light_intersection' to 'traffic_light_intersection_proximity'
    op.alter_column('order', 'traffic_light_intersection', new_column_name='traffic_light_intersection_proximity')
    
    # Drop the old index on 'traffic_light_intersection'
    op.drop_index('idx_order_traffic_light_intersection', table_name='order', postgresql_using='gist')
    
    # Create a new index on the renamed column 'traffic_light_intersection_proximity'
    op.create_index('idx_order_traffic_light_intersection_proximity', 'order', ['traffic_light_intersection_proximity'], unique=False, postgresql_using='gist')
    
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    # Rename the column back to 'traffic_light_intersection'
    op.alter_column('order', 'traffic_light_intersection_proximity', new_column_name='traffic_light_intersection')
    
    # Drop the index on 'traffic_light_intersection_proximity'
    op.drop_index('idx_order_traffic_light_intersection_proximity', table_name='order', postgresql_using='gist')
    
    # Create the original index on 'traffic_light_intersection'
    op.create_index('idx_order_traffic_light_intersection', 'order', ['traffic_light_intersection'], unique=False, postgresql_using='gist')
    
    # ### end Alembic commands ###

