"""Initial migration

Revision ID: a1011c82534a
Revises: 
Create Date: 2025-02-03 18:38:02.288786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1011c82534a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('sessions')
    op.add_column('order', sa.Column('caller_latitude', sa.Float(), nullable=False, default=0 ))
    op.add_column('order', sa.Column('caller_longitude', sa.Float(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'caller_longitude')
    op.drop_column('order', 'caller_latitude')
    #op.create_table('sessions',
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    #sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    #sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    #sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    #)
    #op.create_table('spatial_ref_sys',
    #sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    #sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #a.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    #sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    #)
    # ### end Alembic commands ###
